export {default as Hero } from './hero/heropage/Hero'
export {default as Persian} from './persian/persianThings/Persian'
export {default as Services} from './service/Services'
export {default as AllbestWeek} from './bestweek/allbestweek/AllbestWeek'
export {default as Tabproducts} from './tablatestproducts/tabproducts/Tabproducts'
export {default as _Slider} from './sliderimagetext/slider/_Slider'
export {default as BestSelling} from './bestselling/BestSelling'
export {default as BeautifulIran} from './beautifuliran/BeautifulIran'
export {default as ReadAbout} from './readabout/ReadAbout'
export {default as BestSelling2} from './bestselling 2/BestSelling'
export {default as Blog} from './blog/Blog'
export {default as Footer} from './footer/Footer'